package mealplanner;

import java.sql.*;

public class DatabaseInitializer{
    private static final String DB_URL = "jdbc:postgresql://localhost:5432/meals_db";
    private static final String USER = "postgres";
    private static final String PASS = "1111";
    public static Connection connection;

    public static void initializeDatabase() throws SQLException {
        connection = DriverManager.getConnection(DB_URL, USER, PASS);
        connection.setAutoCommit(true);
        Statement statement = connection.createStatement();

        String createMealsTable = "CREATE TABLE IF NOT EXISTS meals (" +
                                    "category VARCHAR(50) NOT NULL, " +
                                    "meal VARCHAR(100) NOT NULL, " +
                                    "meal_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)";

        String createIngredientsTable = "CREATE TABLE IF NOT EXISTS ingredients (" +
                                        "ingredient VARCHAR(50) NOT NULL, " +
                                        "ingredient_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                                        "meal_id INTEGER REFERENCES meals(meal_id))";

        String createPlanTable = "CREATE TABLE IF NOT EXISTS plan (" +
                                    "plan_id SERIAL PRIMARY KEY, " +
                                    "day_name VARCHAR(10) NOT NULL, " +
                                    "breakfast_meal_id INTEGER REFERENCES meals(meal_id), " +
                                    "lunch_meal_id INTEGER REFERENCES meals(meal_id), " +
                                    "dinner_meal_id INTEGER REFERENCES meals(meal_id))";

        statement.executeUpdate(createMealsTable);
        statement.executeUpdate(createIngredientsTable);
        statement.executeUpdate(createPlanTable);

    }
}
